### ISSUE TITLE
Bitmap format issues

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/format#26]
While trying to use it I've stumbled upon some flaws in the current implementation that I think should be   addressed (I recognize this isn't a popular/efficient format - png is much better f.e. -, but still...).

The main thing is that the code doesn't account for padded width, it just copies the bytes over in chunks of 4, which could result in banded images when written out.
(https://msdn.microsoft.com/en-us/library/windows/desktop/dd318229(v=vs.85).aspx and https://en.wikipedia.org/wiki/BMP_file_format#Bitmap_file_header)

![out_xing_b24 bmp](https://cloud.githubusercontent.com/assets/1266447/8388818/90c4bb84-1c67-11e5-84f5-7a27cb9f5c85.png)

Now... I have a half-baked PR for fixing this, but there's still some grey areas for which I'd like some pointers:
 - my _eventual_ PR of `format.bmp.Data.Header` contains a `bpp` and `paddedWidth` fields for further consumption
 - `Data.pixels` would be in BGR order with padded bytes (so raw bytes with padded ones)
 - both `format.bmp.Writer` and `format.bmp.Tools` would have to change, to account for padded bytes (and reverse the bytes order - RGB instead of BGR)
 - I'd imagine some `build/extract()` methods as in png (maybe reuse them and make them into a _global_ utility class?)

**Comment by ncannasse** [comment]
The common format to represent pixels is BGRA stored in low endian (so bytes in BGRA order). But maybe i should make it more explicit by taking the hxd.Pixels class from Heaps.io and porting it to format, but then it's tight to hxd.BitmapData, etc. https://github.com/ncannasse/heaps/blob/master/hxd/Pixels.hx

**Comment by azrafe7** [comment]
To clarify:

it seems that currently the code would only work with 32bpp bitmaps (https://github.com/HaxeFoundation/format/blob/98ebff699f7132edf8f3811f923a8c89f464e314/format/bmp/Reader.hx#L86-L89), while the common format is 24bpp. Moreover the common way to store BMPs it `bottomToTop` (i.e. line-by-line, starting from the bottom-most one, with bytes padded to be a multiple of 4 - if I understood the spec correctly), and that's why I get a flipped image with weird bandings.

I think that `Data` and `Header` should represent the format in a closer way, and delegate the conversion to more familiar/easier formats to other functions (like `png` and `gif` do, with `exctract___` and `build___` methods). 

I'm not sure it's worth the effort to fix this specific one (due to the fact that BMP is unefficient when compared to png and other formats), but at the same time I thought it would be useful to bring the subject up. 

Having some directions on what is the expected way to write support for other file formats and expand this lib would be great!

**Comment by ncannasse** [comment]
In general, when an image has been decoded in format library, it's usually represented in memory / bytes as a top-down 32bits data.

**Comment by azrafe7** [comment]
Yes, that's what `extractARGB/BGRA()` would eventually do. But do you agree that `Data` should represent the binary file more closely (so that, f.e., modifying it in place and writing it back to disk doesn't need any type of conversion)?

**Comment by ncannasse** [comment]
yes, I agree, it should be as much near from the file data, especially if it's read directly as it.
