### ISSUE TITLE
Indexed color PNG reading

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/format#30]
The code for filtering ColIndexed PNG is not correct : instead of applying the filter to the color, it is necessary to apply it to the bytes, for instance by prefiltering the line before decoding it.
(reported by benjamin with an example png)

**Comment by Yanrishatum** [comment]
1. Is this issue still relevant?
2. If yes, can you post an example png?

**Comment by ncannasse** [comment]
Yes, here's the buggy file
![gfx](https://cloud.githubusercontent.com/assets/1022912/19275089/d311e5a4-8fd2-11e6-8468-46ebfc02f2f6.png)

**Comment by Yanrishatum** [comment]
Hm. Just tested this image, and it seems to be perfectly normal with current PNG `Reader`/`Writer` and `extract32` version.  
Compared as simple `Reader->Writer` as well as `Reader -> extract32 -> build32BGRA -> Writer`.  
And it seems that there is already prefiltering in place: https://github.com/HaxeFoundation/format/blob/master/format/png/Tools.hx#L274-L315

**Comment by ncannasse** [comment]
Right, it seems I didn't remember fixing it myself in b14232f1217118b712c95f23b890927b3f6b682d, sorry for the wasted time
