### ISSUE TITLE
partial rewrite of agal.Reg

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/format#31]
Hi,

The worst offender (alloc/cpu) on h3d is often the shader parameter management on as3. I isolated the root of all evil  to :

```
typedef Reg = {
	var t : RegType;
	var index : Int;
	var swiz : Swizzle;
	var access : Null<{ t : RegType, comp : C, offset : Int }>;
}
```

I will rewrite this as class Reg <...>

@ncannasse Are you interested in a pull request ?

Bisous !

**Comment by ncannasse** [comment]
Sure.

**Comment by delahee** [comment]
Nice. Here on massive fx sequences, we jumped from 150ms to 3ms frames. i'll send something soon.

**Comment by delahee** [comment]
done in #32
