### ISSUE TITLE
Version 3.2.1 Breaks Flambe Flash Build

### ISSUE THREAD

**Issue by quinnhoener** [HaxeFoundation/format#41]
After updating to Format 3.2.1, I'm getting the following errors when running a flash build from Flambe. 

Building: build/web/targets/main-flash.swf
haxe --connect 6001 -main Main -D flambe_webgl_enable_linear -D haxeJSON -lib flambe -cp src -dce full -debug --no-opt --no-inline --macro flambe.platform.ManifestBuilder.use("build/web/assets") --flash-strict -swf-header 640:480:60:000000 -D fdb -D advanced-telemetry -swf-version 11.2 -swf build/web/targets/main-flash.swf
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:761: characters 13-14 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:761: characters 13-14 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:101: characters 3-90 : { t : format.agal.RegType, swiz : Null<format.agal.Swizzle>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:103: characters 2-136 : { t : format.agal.RegType, swiz : format.agal.Swizzle, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:591: characters 12-13 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:591: characters 12-13 : For function argument 'src'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:598: characters 15-16 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:598: characters 15-16 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:599: characters 14-15 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:599: characters 14-15 : For function argument 'src'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:623: characters 8-9 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:623: characters 8-9 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:568: characters 18-19 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:568: characters 18-19 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:569: characters 3-8 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:573: characters 18-19 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:573: characters 18-19 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:574: characters 3-8 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:500: characters 18-77 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:500: characters 18-77 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:501: characters 18-77 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:501: characters 18-77 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:502: characters 18-77 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:502: characters 18-77 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:503: characters 15-74 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:503: characters 15-74 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:524: characters 12-30 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:524: characters 12-30 : For function argument 'x'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:525: characters 12-52 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:525: characters 12-52 : For function argument 'x'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:526: characters 12-52 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:526: characters 12-52 : For function argument 'x'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:507: characters 18-77 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:507: characters 18-77 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:508: characters 18-77 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:508: characters 18-77 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:509: characters 15-74 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:509: characters 15-74 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:542: characters 12-31 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:542: characters 12-31 : For function argument 'x'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:543: characters 12-53 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:543: characters 12-53 : For function argument 'x'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:639: characters 5-9 : a1 : format.agal.Reg -> r1 : format.agal.Reg -> r2 : format.agal.Reg -> Void should be a2 : format.agal.Reg -> a : format.agal.Reg -> b : format.agal.Reg -> Null<format.agal.Opcode>
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:639: characters 5-9 : Cannot unify return types
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:639: characters 5-9 : Void should be Null<format.agal.Opcode>
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:639: characters 5-9 : Void should be format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:649: characters 4-11 : dst : format.agal.Reg -> a : format.agal.Reg -> b : format.agal.Reg -> format.agal.Opcode should be Void
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:633: characters 3-7 : Void should be dst : format.agal.Reg -> a : format.agal.Reg -> b : format.agal.Reg -> format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:668: characters 20-21 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:668: characters 20-21 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:669: characters 14-15 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:669: characters 14-15 : For function argument 'src'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:675: characters 19-20 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:675: characters 19-20 : For function argument 'r'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:676: characters 8-9 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:676: characters 8-9 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:677: characters 49-50 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:677: characters 49-50 : For function argument 'a'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:684: characters 9-10 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:684: characters 9-10 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:704: characters 49-101 : { t : format.agal.RegType, swiz : Array<format.agal.C>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:704: characters 49-101 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:704: characters 3-7 : Void should be dst : format.agal.Reg -> v : format.agal.Reg -> format.agal.Opcode
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:712: characters 8-9 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:712: characters 8-9 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:742: characters 23-27 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:742: characters 23-27 : For function argument 'pt'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:188: characters 13-65 : { t : format.agal.RegType, swiz : Unknown<1>, index : Int, access : Unknown<0> } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:188: characters 13-65 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:200: characters 14-15 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:200: characters 14-15 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:201: characters 8-9 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:201: characters 8-9 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:206: characters 12-13 : { t : format.agal.RegType, swiz : Null<Array<format.agal.C>>, index : Int, access : { t : format.agal.RegType, offset : Int, comp : format.agal.C } } should be format.agal.Reg
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:206: characters 12-13 : For function argument 'dst'
/usr/lib/haxe/lib/hxsl/2,0,5/hxsl/AgalCompiler.hx:233: characters 3-156 : { t : format.agal.RegType, swiz : format.agal.Swizzle, index : Int, access : Null<{ t : format.agal.RegType, offset : Int, comp : format.agal.C }> } should be format.agal.Reg
[Finished in 1.8s with exit code 1]

Setting format back to 3.2.0 resolves the issue for me.

**Comment by ncannasse** [comment]
Thanks for the report I've just pushed an update for hxsl as well.
