### ISSUE TITLE
[SWF] Implement LZMA

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/format#44]
It seems some SWF are compressed using LZMA, see : 
https://github.com/OpenGG/swfzip/blob/master/swfzip.py

**Comment by Simn** [comment]
I don't think opening issues like this is going to achieve anything unless you plan to work on this yourself.

**Comment by ncannasse** [comment]
Indeed. Wait for a PR :)

**Comment by clemos** [comment]
Maybe you should disable Issues if you want PRs only ?
Because I used the exact same workflow for https://github.com/HaxeFoundation/format/issues/37 (report the issue for info, work on it, PR) 
and it didn't seem to be a problem then.
Happy new year :D

**Comment by ncannasse** [comment]
I'm accepting issues when they are issues, not features requests such as adding a complete new format. You can still submit a PR without having to open an issue beforehand :)

**Comment by clemos** [comment]
The LZMA algorithm alone is a new feature indeed.
But I would say it's an actual bug for `format.swf.*`, as it throws an "Invalid SWF" error for SWFs that are compressed this way.
If you want, I can make a PR for `format.swf.*` that throws a more informative "LZMA is not implemented" when the `format.swf.Reader` encounters this compression format ?
I plan to work on implementing LZMA anyway, but I think it would be nice to have that in the meantime.

**Comment by ncannasse** [comment]
@clemos your original issue was more about adding full LZMA support but sure, that makes sense to add proper error in SWF format until it's supported
