### ISSUE TITLE
format-style libraries listing

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/format#57]
So, `format` is more general-purpose library, and when I've done [`tmx`](https://github.com/yanrishatum/haxe-format-tiled) format-style library I thought it won't fit well into the main library.  
But I think when libraries that use same style as `format` but is not general-purpose ones being developed - they worth mentioning here.  
Ugh, sorry for a bit clumsy explaination.  
In tl;dr: Add additional column in readme listing other libraries that have same style as `format` and provide support for less-general formats.

**Comment by ncannasse** [comment]
Given the modular approach of format, I don't see any problem adding less "general purpose" format support as long as we have maintainer for it and the format itself is well supported enough (tmx is quite a standard so often used).

**Comment by Yanrishatum** [comment]
Well then, I'll do a pull request when next Tiled version will come out, as that will let me to reimplement properties with support of typing (in newest Tiled, properties have type and can be not only Strings, but as well numbers, filepaths, booleans, etc) without caring about backward-compatability with `Map<String, String>`. Yet this issue is about overall, not only TMX format.
